### PR TITLE
fix for removed elements when symfony's empty_data option is enabled

### PR DESCRIPTION
**Pull request by JarekW**

### CODE REVIEW

**Comment by JarekW** [comment]
if fail on symfony 2.8@dev. Should it be in allowed failures as it is unstable?

**Comment by JarekW** [comment]
@fsi-open
?

**Comment by szymach** [comment]
I'd put unstable versions in the 'allow_failures' section

**Comment by JarekW** [comment]
@fsi-open

**Comment by szymach** [comment]
:+1:

**Comment by chives** [comment]
:+1:

**Comment by rn0** [comment]
:+1:

**Pull request merged**
